[package]
name = "cmaybenot"
description = "A small FFI wrapper around Maybenot"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
maybenot = "1.1.1"
thiserror = "1.0"